### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by 09wattry**
* I have added a DockerFile to allow images to be built.
* Added docker-compose file to allow for easy docker use. 
* Updated README to include updates.
* Would appreciate any suggestions.

### CODE REVIEW

**Comment by slmg** [comment]
This was merged quite quickly, I had a pending review as requested in #5

**Comment by 09wattry** [comment]
I have been adding CICD to the project and I have free time now so I wanted to test the pipelines. If you add comments or put in a PR we can work on any changes together.

**Comment by slmg** [comment]
Ok np, I'm going to put in a PR to avoid to have stale comments here.

Two remarks from my review:
* Out of interest, why choosing Github Actions over [DockerHub automated builds](https://docs.docker.com/docker-hub/builds/)?
* Is it intentional to have two *installer.js*, at the root and inside the src dir?

**Comment by 09wattry** [comment]
@slmg 

1. There is no real strategy other than it's easier for me to manage everything in one place. I do have a docker automated build setup, but I don't think it's really necessary to maintain a docker image repo since if you have docker and git, you can easily build the image locally and use this project. What do you feel the benefits of a dedicated image are?
2. That was a mistake, so next time I'll wait a little longer before I make a merge.

Thanks for the feedback.

If you do make a pull request please set your branch to <your username>/issue-#. This is a standard I like to keep so when we look at history we have quick access to what I need.

I appreciate your time, hopefully we can collaborate on more projecs

**Comment by slmg** [comment]
Thanks, it's also appreciated you take time to collaborate :wink: 

>I do have a docker automated build setup, but I don't think it's really necessary to maintain a docker image repo since if you have docker and git, you can easily build the image locally and use this project. What do you feel the benefits of a dedicated image are?

The benefits are multiple:
1. It allows a direct run without needing to `git clone`, which is convenient and faster.
1. An already built image is as useful as any already built software. It would be a bit annoying to have to build clone and build everything from source.
1. Some users may use a different system such as Kubernetes to run docker images, which means they may not have the Docker CLI installed at all on their machines. So they would be unable to build Docker images.
1. DockerHub allows to publish images only on specific tag, which can be a useful deployment process.
1. A public docker image is very low maintenance and convenient to everyone so I do not feel there are any strong reasons not to have one

**Pull request merged**
